"""Regenerates murmur/ui/web/icons.js from Phosphor Icons (regular weight, MIT licence).

    python scripts/fetch_icons.py
"""
import json
import re
import urllib.request
from pathlib import Path

BASE = "https://raw.githubusercontent.com/phosphor-icons/core/HEAD/assets/regular/{}.svg"
# Our name -> Phosphor name.
ICONS = {
    "home": "house", "settings": "sliders-horizontal", "info": "info", "copy": "copy",
    "trash": "trash", "check": "check", "search": "magnifying-glass", "mic": "microphone",
    "folder": "folder-open", "external": "arrow-square-out", "zap": "lightning",
    "alert": "warning-circle", "lock": "lock-simple", "keyboard": "keyboard", "github": "github-logo",
}
OUT = Path(__file__).resolve().parent.parent / "murmur" / "ui" / "web" / "icons.js"

icons = {}
for name, phosphor in ICONS.items():
    svg = urllib.request.urlopen(BASE.format(phosphor)).read().decode()
    inner = re.search(r"<svg[^>]*>(.*)</svg>", svg, re.S).group(1).strip()
    icons[name] = inner
OUT.write_text(
    "// Phosphor Icons, regular weight (https://phosphoricons.com, MIT licence).\n"
    "// Generated by scripts/fetch_icons.py; do not edit by hand.\n"
    f"const ICONS = {json.dumps(icons, indent=2)};\n",
    encoding="utf-8",
)
print(f"Wrote {len(icons)} icons to {OUT}")
